"""Fix relationships

Revision ID: 08d399f46639
Revises: c19aa3df21c9
Create Date: 2020-09-05 18:33:45.503131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d399f46639'
down_revision = 'c19aa3df21c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'count_crimes_by_cities', 'city_codes', ['city_code'], ['city_code'])
    op.create_foreign_key(None, 'crime_counts_by_types', 'crime_codes', ['crime_code'], ['crime_code'])
    op.create_foreign_key(None, 'features', 'city_codes', ['city_code'], ['city_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.drop_constraint(None, 'crime_counts_by_types', type_='foreignkey')
    op.drop_constraint(None, 'count_crimes_by_cities', type_='foreignkey')
    # ### end Alembic commands ###
