"""Add year to crime counts by types

Revision ID: 79fa3c229803
Revises: f440f5f95db4
Create Date: 2020-09-05 20:03:17.366291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fa3c229803'
down_revision = 'f440f5f95db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'count_crimes_by_cities', 'city_codes', ['city_code'], ['city_code'])
    op.add_column('crime_counts_by_types', sa.Column('year', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crime_counts_by_types', 'crime_codes', ['crime_code'], ['crime_code'])
    op.create_foreign_key(None, 'features', 'city_codes', ['city_code'], ['city_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.drop_constraint(None, 'crime_counts_by_types', type_='foreignkey')
    op.drop_column('crime_counts_by_types', 'year')
    op.drop_constraint(None, 'count_crimes_by_cities', type_='foreignkey')
    # ### end Alembic commands ###
