"""Add unqiue to features object_id

Revision ID: ad42bdb1fb7d
Revises: bfe0f2f7eae6
Create Date: 2020-09-06 21:49:08.243052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad42bdb1fb7d'
down_revision = 'bfe0f2f7eae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'count_crimes_by_cities', 'city_codes', ['city_code'], ['city_code'])
    op.create_foreign_key(None, 'crime_counts_by_types', 'crime_codes', ['crime_code'], ['crime_code'])
    op.drop_index('ix_features_object_id', table_name='features')
    op.create_index(op.f('ix_features_object_id'), 'features', ['object_id'], unique=True)
    op.create_foreign_key(None, 'features', 'city_codes', ['city_code'], ['city_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.drop_index(op.f('ix_features_object_id'), table_name='features')
    op.create_index('ix_features_object_id', 'features', ['object_id'], unique=False)
    op.drop_constraint(None, 'crime_counts_by_types', type_='foreignkey')
    op.drop_constraint(None, 'count_crimes_by_cities', type_='foreignkey')
    # ### end Alembic commands ###
