"""Reformat CrimesCountPeriods table

Revision ID: bfe0f2f7eae6
Revises: 79fa3c229803
Create Date: 2020-09-06 16:19:31.781222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfe0f2f7eae6'
down_revision = '79fa3c229803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'count_crimes_by_cities', 'city_codes', ['city_code'], ['city_code'])
    op.create_foreign_key(None, 'crime_counts_by_types', 'crime_codes', ['crime_code'], ['crime_code'])
    op.add_column('crimes_count_periods', sa.Column('json_data', sa.Text(), nullable=True))
    op.drop_column('crimes_count_periods', 'crimes_count')
    op.drop_column('crimes_count_periods', 'period')
    op.create_foreign_key(None, 'features', 'city_codes', ['city_code'], ['city_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.add_column('crimes_count_periods', sa.Column('period', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('crimes_count_periods', sa.Column('crimes_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('crimes_count_periods', 'json_data')
    op.drop_constraint(None, 'crime_counts_by_types', type_='foreignkey')
    op.drop_constraint(None, 'count_crimes_by_cities', type_='foreignkey')
    # ### end Alembic commands ###
