"""Fix relationships

Revision ID: f440f5f95db4
Revises: 08d399f46639
Create Date: 2020-09-05 18:40:12.306036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f440f5f95db4'
down_revision = '08d399f46639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'count_crimes_by_cities', 'city_codes', ['city_code'], ['city_code'])
    op.create_foreign_key(None, 'crime_counts_by_types', 'crime_codes', ['crime_code'], ['crime_code'])
    op.create_foreign_key(None, 'features', 'city_codes', ['city_code'], ['city_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.drop_constraint(None, 'crime_counts_by_types', type_='foreignkey')
    op.drop_constraint(None, 'count_crimes_by_cities', type_='foreignkey')
    # ### end Alembic commands ###
